version: '3'

services:
  web:
    build: .
    container_name: electronic_exam_web
    command: python manage.py runserver 0.0.0.0:9000
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - .:/app
      - ./media:/app/media
    networks:
      - exam_net
    environment:
      - OPENAI_API_KEY=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

  db:
    image: postgres:latest
    container_name: electronic_exam_db
    environment:
      POSTGRES_DB: electronic_board
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Engineering
    ports:
      - "5435:5432"
    networks:
      - exam_net

networks:
  exam_net:
